var serperiorHP = 75;
var serperiorNum = 497;
var serperiorType = "Grass";
var serperiorBestMove = "Leaf Storm";
var serperiorLastEvo = True;
var serperiorAttack = 75;
var serperiorDefense =95;
var serperiorSpecial_Attack = 113;
serperiorHP=  serperiorHP - 50;
